language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6-heroku
  on: master
  skip_cleanup: true
  api_key: 053515c2-bdb0-4be0-a0ed-eaab6e381651
